title: Jake Bottenberg
description: Computer software engineer with experience focused on customer service and internet technology. Skilled primarily in C++ and Python coding languages. I aspire to focus my efforts on growing myself professionally, while also creating video games with Unreal Engine and Godot game engines on the side.
remote_theme: tuur29/pages-themes-cayman

show_downloads: true
google_analytics:
google_analytics_anonymize: false
darkmode: true
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: https://cdn.pixabay.com/photo/2023/09/14/10/27/face-logo-8252748_640.png # Either absolute or relative url
syntax_theme: # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: https://github.com/tuur29/pages-themes-cayman
      zip_title: Title
      zip_hide: true
      tar_url: https://github.com/tuur29/pages-themes-cayman
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"