title: Jake Bottenberg
description: Computer software engineer with experience focused on customer service and internet technology. Skilled primarily in C++ and Python coding languages. I aspire to focus my efforts on growing myself professionally, while also creating video games with Unreal Engine and Godot game engines on the side.
theme: jekyll-theme-cayman

show_downloads: true
google_analytics:
google_analytics_anonymize: false
darkmode: true
hide_first_title: false # Useful if README.md is used on both github and pages
